# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainUi(object):
    def setupUi(self, MainUi):
        MainUi.setObjectName("MainUi")
        MainUi.resize(1104, 882)
        MainUi.setStyleSheet("QWidget {\n"
"\n"
"background-color: \"#232429\"\n"
"\n"
"}")
        self.ExecuteQuery = QtWidgets.QPushButton(MainUi)
        self.ExecuteQuery.setGeometry(QtCore.QRect(890, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ExecuteQuery.setFont(font)
        self.ExecuteQuery.setStyleSheet("background-color: \"#1d5ffe\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"font: 14px")
        self.ExecuteQuery.setObjectName("ExecuteQuery")
        self.input_comboBox = QtWidgets.QComboBox(MainUi)
        self.input_comboBox.setGeometry(QtCore.QRect(20, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_comboBox.setFont(font)
        self.input_comboBox.setStyleSheet("background-color: \"#2b2f3b\";\n"
"color: \"#eaebf2\";\n"
"font: 12px")
        self.input_comboBox.setCurrentText("")
        self.input_comboBox.setObjectName("input_comboBox")
        self.input_plainTextEdit = QtWidgets.QPlainTextEdit(MainUi)
        self.input_plainTextEdit.setGeometry(QtCore.QRect(180, 50, 871, 231))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_plainTextEdit.setFont(font)
        self.input_plainTextEdit.setStyleSheet("color: \"#eaebf2\";\n"
"font: 12px;\n"
"padding: 5px")
        self.input_plainTextEdit.setObjectName("input_plainTextEdit")
        self.label = QtWidgets.QLabel(MainUi)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: \"#6a6b79\";\n"
"font: 12px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainUi)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: \"#6a6b79\";\n"
"font: 12px")
        self.label_2.setObjectName("label_2")
        self.input_treeWidget = QtWidgets.QTreeWidget(MainUi)
        self.input_treeWidget.setGeometry(QtCore.QRect(20, 130, 151, 731))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.input_treeWidget.setFont(font)
        self.input_treeWidget.setStyleSheet("color: \"#eaebf2\";\n"
"font: 12px")
        self.input_treeWidget.setColumnCount(1)
        self.input_treeWidget.setObjectName("input_treeWidget")
        self.input_treeWidget.headerItem().setText(0, "1")
        self.label_3 = QtWidgets.QLabel(MainUi)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: \"#6a6b79\";\n"
"font: 12px")
        self.label_3.setObjectName("label_3")
        self.label_qep = QtWidgets.QLabel(MainUi)
        self.label_qep.setGeometry(QtCore.QRect(180, 350, 871, 211))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_qep.setFont(font)
        self.label_qep.setStyleSheet("color: \"#eaebf2\";\n"
"font: 12px;\n"
"background-color: \"#2b2f3b\";\n"
"padding: 5px")
        self.label_qep.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_qep.setWordWrap(True)
        self.label_qep.setObjectName("label_qep")
        self.label_5 = QtWidgets.QLabel(MainUi)
        self.label_5.setGeometry(QtCore.QRect(180, 330, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: \"#6a6b79\";\n"
"font: 12px")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(MainUi)
        self.label_6.setGeometry(QtCore.QRect(180, 590, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: \"#6a6b79\";\n"
"font: 12px")
        self.label_6.setObjectName("label_6")
        self.label_graph = PlotWidget(MainUi)
        self.label_graph.setGeometry(QtCore.QRect(180, 610, 871, 251))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_graph.setFont(font)
        self.label_graph.setStyleSheet("color: \"#eaebf2\";\n"
"font: 12px;\n"
"background-color: \"#2b2f3b\";\n"
"padding: 5px;\n"
"border-width: 0px;")
        self.label_graph.setObjectName("label_graph")
        self.ExecuteQuery.raise_()
        self.input_comboBox.raise_()
        self.input_plainTextEdit.raise_()
        self.label.raise_()
        self.input_treeWidget.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_qep.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_graph.raise_()

        self.retranslateUi(MainUi)
        QtCore.QMetaObject.connectSlotsByName(MainUi)

    def retranslateUi(self, MainUi):
        _translate = QtCore.QCoreApplication.translate
        MainUi.setWindowTitle(_translate("MainUi", "CZ4031 Group 58 Project 2"))
        self.ExecuteQuery.setText(_translate("MainUi", "⯈ Run Query"))
        self.label.setText(_translate("MainUi", "Choose database"))
        self.label_2.setText(_translate("MainUi", "Tables:"))
        self.label_3.setText(_translate("MainUi", "Input a query:"))
        self.label_qep.setText(_translate("MainUi", "The Query Execution Plan in natural language will be printed here after you click \"Run Query\""))
        self.label_5.setText(_translate("MainUi", "HOW // Query Plan:"))
        self.label_6.setText(_translate("MainUi", "WHY // Alternative Plan Comparisons:"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUi = QtWidgets.QWidget()
    ui = Ui_MainUi()
    ui.setupUi(MainUi)
    MainUi.show()
    sys.exit(app.exec())
