# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1106, 889)
        Form.setStyleSheet("QWidget {\n"
                           "\n"
                           "background-color: \"#232429\"\n"
                           "\n"
                           "}")
        self.ExecuteQuery = QtWidgets.QPushButton(Form)
        self.ExecuteQuery.setGeometry(QtCore.QRect(890, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ExecuteQuery.setFont(font)
        self.ExecuteQuery.setStyleSheet("background-color: \"#1d5ffe\";\n"
                                        "color: white;\n"
                                        "border-style: outset;\n"
                                        "border-radius: 10px;\n"
                                        "font: 14px")
        self.ExecuteQuery.setObjectName("ExecuteQuery")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 151, 41))
        self.comboBox.setStyleSheet("background-color: \"#2b2f3b\";\n"
                                    "color: \"#eaebf2\";\n"
                                    "font: 12px")
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 50, 871, 231))
        self.plainTextEdit.setStyleSheet("color: \"#eaebf2\";\n"
                                         "font: 12px")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: \"#6a6b79\";\n"
                                 "font: 12px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: \"#6a6b79\";\n"
                                   "font: 12px")
        self.label_2.setObjectName("label_2")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(20, 130, 151, 731))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.treeWidget.setFont(font)
        self.treeWidget.setStyleSheet("color: \"#eaebf2\";\n"
                                      "font: 12px")
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: \"#6a6b79\";\n"
                                   "font: 12px")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CZ4031 Group 58 Project 2"))
        self.ExecuteQuery.setText(_translate("Form", "⯈ Run Query"))
        self.label.setText(_translate("Form", "Choose database"))
        self.label_2.setText(_translate("Form", "Tables:"))
        self.label_3.setText(_translate("Form", "Input a query:"))

        def login(self):
            self.label.setText


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
